# Generated by Django 4.1.6 on 2023-02-02 20:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "location",
                    models.TextField(help_text="Where did you stay for the day."),
                ),
                ("sex", models.BooleanField()),
                (
                    "sleep_hours",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MaxValueValidator(24),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="hours of sleep",
                    ),
                ),
                (
                    "work_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MaxValueValidator(24),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="hours of work",
                    ),
                ),
                (
                    "parenting_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MaxValueValidator(24),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="hours of parenting",
                    ),
                ),
                (
                    "personal_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MaxValueValidator(24),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="hours of personal time",
                    ),
                ),
                (
                    "social_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MaxValueValidator(24),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="hours of social time",
                    ),
                ),
                ("exercise_minutes", models.PositiveSmallIntegerField(default=0)),
                ("calories_burned", models.PositiveSmallIntegerField(default=0)),
                (
                    "sweets_eaten",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "None"),
                            (1, "A little"),
                            (2, "A moderate amount"),
                            (3, "A large amount"),
                            (4, "An excessive amount"),
                        ],
                        validators=[
                            django.core.validators.MaxValueValidator(4),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "stress_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "None"),
                            (1, "A little"),
                            (2, "A moderate amount"),
                            (3, "A large amount"),
                            (4, "An excessive amount"),
                        ],
                        validators=[
                            django.core.validators.MaxValueValidator(4),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "motivation_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "None"),
                            (1, "A little"),
                            (2, "A moderate amount"),
                            (3, "A large amount"),
                            (4, "An excessive amount"),
                        ],
                        validators=[
                            django.core.validators.MaxValueValidator(4),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "energy_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "None"),
                            (1, "A little"),
                            (2, "A moderate amount"),
                            (3, "A large amount"),
                            (4, "An excessive amount"),
                        ],
                        validators=[
                            django.core.validators.MaxValueValidator(4),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "physical_health_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "None"),
                            (1, "A little"),
                            (2, "A moderate amount"),
                            (3, "A large amount"),
                            (4, "An excessive amount"),
                        ],
                        validators=[
                            django.core.validators.MaxValueValidator(4),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "illness_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "None"),
                            (1, "A little"),
                            (2, "A moderate amount"),
                            (3, "A large amount"),
                            (4, "An excessive amount"),
                        ],
                        validators=[
                            django.core.validators.MaxValueValidator(4),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
            ],
        ),
    ]
