# Generated by Django 4.1.6 on 2023-02-08 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="overall_mood",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Very Depressed"),
                    (1, "Depressed"),
                    (2, "Mildly Depressed"),
                    (3, "Low"),
                    (4, "Good"),
                    (5, "Elevated"),
                    (6, "Mildly Manic"),
                    (7, "Manic"),
                    (8, "Very Manic"),
                ],
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(8),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
