# Generated by Django 4.1.6 on 2023-02-09 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_record_overall_mood"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="concentration_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "A little"),
                    (2, "A moderate amount"),
                    (3, "A large amount"),
                    (4, "An excessive amount"),
                ],
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(4),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
