# Generated by Django 4.1.6 on 2023-02-16 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_record_irritability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="record",
            name="eating",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "None"), (1, "Light"), (2, "Normal"), (3, "Excessive")],
                default=2,
                validators=[
                    django.core.validators.MaxValueValidator(3),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
