# Generated by Django 4.1.6 on 2023-03-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_alter_record_options_record_eating"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="overnight_parenting",
            field=models.BooleanField(default=True, verbose_name="parenting overnight"),
        ),
        migrations.AddField(
            model_name="record",
            name="stress_score",
            field=models.FloatField(
                default=None, null=True, verbose_name="stress score"
            ),
        ),
    ]
