# Generated by Django 4.1.6 on 2023-04-18 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0010_tag_record_record_owner_date_unique_tag_owner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Medication Name")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="record",
            name="stress_score",
            field=models.FloatField(
                blank=True, default=None, null=True, verbose_name="stress score"
            ),
        ),
        migrations.CreateModel(
            name="MedicationDosage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosage", models.TextField(verbose_name="Dosage")),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.medication",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="record",
            name="medications_taken",
            field=models.ManyToManyField(to="tracker.medicationdosage"),
        ),
        migrations.AddConstraint(
            model_name="medicationdosage",
            constraint=models.UniqueConstraint(
                fields=("owner", "medication", "dosage"),
                name="medication_dosage_owner_medication_dosage_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="medication",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="medication_owner_name_unique"
            ),
        ),
    ]
